# -*- coding: utf-8 -*-
"""database

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b576IvMpoD2Z9lYV9komX_KUx11IVdCe
"""

# -------------------------------
# Cell 1: Database Setup
# -------------------------------
# This module sets up a SQLite database ("venues.db") using SQLAlchemy.
# It defines the Venue model with fields such as name, address, city, phone, website, latitude, longitude, and source.

from sqlalchemy import create_engine, Column, Integer, String, Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# Create an engine for a SQLite database file
engine = create_engine("sqlite:///venues.db", echo=False)

# Base class for declarative models
Base = declarative_base()

# Define the Venue model (table)
class Venue(Base):
    __tablename__ = 'venues'
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, nullable=False)
    address = Column(String)
    city = Column(String)
    phone = Column(String)
    website = Column(String)
    latitude = Column(Float)
    longitude = Column(Float)
    source = Column(String)  # The domain or URL where the venue was scraped from

# Create the table(s) in the database (if they do not exist yet)
Base.metadata.create_all(engine)

# Create a session factory for database operations
SessionLocal = sessionmaker(bind=engine)

print("Database setup complete.")