# -*- coding: utf-8 -*-
"""DATATHON_DATAFORCE_MAIN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rAdYplKkt7I9Kt6PzN7badr6GbEqOuix
"""

# RENAME THIS TO MAIN AND DOWNLOAD AS .py

# main.py - FastAPI Backend API
# -------------------------------
# This module creates the FastAPI app that exposes two endpoints:
# 1. POST /scrape : Accepts a URL, triggers the scraping function (from Cell 2),
#                   stores the results into the SQLite database (Cell 1),
#                   and returns the scraped venue data.
# 2. GET /venues  : Returns venues stored in the database filtered by optional
#                   query parameters (city and/or keyword).
#
# IMPORTANT: Save this file as main.py and run it outside of Google Colab using uvicorn.
#
# Required: Make sure you have already run Cell 1 and Cell 2 in your environment
# so that SessionLocal, Venue, and the scraping functions (scrape_venues_from_url, etc.)
# are available. You may choose to combine these modules or import them as needed.

from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel
from typing import List, Optional

# --- Import the database and scraping modules ---
# If you have the code from Cell 1 and Cell 2 in the same notebook, you can simply run them first.
# Otherwise, if you separate them into modules, import like:
# from database_module import SessionLocal, Venue
# from scraping_module import scrape_venues_from_url

# For this example, we assume that the code from Cell 1 and Cell 2 is already executed in the environment.

app = FastAPI(title="Wedding Venue Search API")

# Pydantic model for serializing Venue data in API responses
class VenueModel(BaseModel):
    id: Optional[int]
    name: str
    address: Optional[str]
    city: Optional[str]
    phone: Optional[str]
    website: Optional[str]
    latitude: Optional[float]
    longitude: Optional[float]
    source: Optional[str]

    class Config:
        orm_mode = True

# POST endpoint to trigger scraping for a given URL
@app.post("/scrape", response_model=List[VenueModel])
def trigger_scrape(url: str):
    """
    Trigger the scraping process for the provided URL.
    This endpoint:
      - Uses the scraping function (scrape_venues_from_url from Cell 2)
      - Stores new venues in the database (using SessionLocal from Cell 1)
      - Returns the list of scraped (or already stored) venues.
    """
    venues_data = scrape_venues_from_url(url)
    if not venues_data:
        raise HTTPException(status_code=404, detail="No venues found or an error occurred during scraping.")

    session = SessionLocal()
    saved_venues = []
    for data in venues_data:
        # Check for duplicates by name and source
        existing = session.query(Venue).filter_by(name=data["name"], source=data["source"]).first()
        if existing is None:
            venue = Venue(**data)
            session.add(venue)
            session.commit()
            session.refresh(venue)
            saved_venues.append(venue)
        else:
            saved_venues.append(existing)
    session.close()
    return [VenueModel.from_orm(v) for v in saved_venues]

# GET endpoint to query venues by optional filters
@app.get("/venues", response_model=List[VenueModel])
def query_venues(
    city: Optional[str] = Query(None, description="Filter venues by city"),
    keyword: Optional[str] = Query(None, description="Filter venues by keyword in venue name")
):
    """
    Query the stored venues from the database.
    You can filter results by 'city' and/or a 'keyword' in the venue name.
    """
    session = SessionLocal()
    query = session.query(Venue)
    if city:
        query = query.filter(Venue.city.ilike(f"%{city}%"))
    if keyword:
        query = query.filter(Venue.name.ilike(f"%{keyword}%"))
    venues = query.all()
    session.close()
    return [VenueModel.from_orm(v) for v in venues]

# -------------------------------
# Note to the Developer:
#
# Do not call uvicorn.run(app, ...) here when deploying in production.
#
# To run the FastAPI backend outside of Google Colab:
# 1. Save this file as main.py.
# 2. In your terminal, navigate to the directory containing main.py.
# 3. Execute:
#       uvicorn main:app --host 0.0.0.0 --port 8000 --reload
#
# 4. Visit http://127.0.0.1:8000/docs to see the interactive API documentation.
# -------------------------------